//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//

using System;
using System.Linq;

using Rock.Data;

namespace Rock.Core
{
    /// <summary>
    /// Note Service class
    /// </summary>
    public partial class NoteService : Service<Note, NoteDto>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NoteService"/> class
        /// </summary>
        public NoteService()
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NoteService"/> class
        /// </summary>
        public NoteService(IRepository<Note> repository) : base(repository)
        {
        }

        /// <summary>
        /// Creates a new model
        /// </summary>
        public override Note CreateNew()
        {
            return new Note();
        }

        /// <summary>
        /// Query DTO objects
        /// </summary>
        /// <returns>A queryable list of DTO objects</returns>
        public override IQueryable<NoteDto> QueryableDto( )
        {
            return QueryableDto( this.Queryable() );
        }

        /// <summary>
        /// Query DTO objects
        /// </summary>
        /// <returns>A queryable list of DTO objects</returns>
        public IQueryable<NoteDto> QueryableDto( IQueryable<Note> items )
        {
            return items.Select( m => new NoteDto()
                {
                    IsSystem = m.IsSystem,
                    NoteTypeId = m.NoteTypeId,
                    EntityId = m.EntityId,
                    SourceTypeValueId = m.SourceTypeValueId,
                    Caption = m.Caption,
                    Date = m.Date,
                    IsAlert = m.IsAlert,
                    Text = m.Text,
                    Id = m.Id,
                    Guid = m.Guid,
                });
        }
    }
}
