//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System;
using System.Collections.Generic;
using System.Dynamic;

using Rock.Data;

namespace Rock.Core
{
    /// <summary>
    /// Data Transfer Object for NoteType object
    /// </summary>
    public partial class NoteTypeDto : IDto
    {

#pragma warning disable 1591
        public bool IsSystem { get; set; }
        public int EntityTypeId { get; set; }
        public string EntityTypeQualifierColumn { get; set; }
        public string EntityTypeQualifierValue { get; set; }
        public string Name { get; set; }
        public int? SourcesTypeId { get; set; }
        public int Id { get; set; }
        public Guid Guid { get; set; }
#pragma warning restore 1591

        /// <summary>
        /// Instantiates a new DTO object
        /// </summary>
        public NoteTypeDto ()
        {
        }

        /// <summary>
        /// Instantiates a new DTO object from the entity
        /// </summary>
        /// <param name="noteType"></param>
        public NoteTypeDto ( NoteType noteType )
        {
            CopyFromModel( noteType );
        }

        /// <summary>
        /// Creates a dictionary object.
        /// </summary>
        /// <returns></returns>
        public virtual Dictionary<string, object> ToDictionary()
        {
            var dictionary = new Dictionary<string, object>();
            dictionary.Add( "IsSystem", this.IsSystem );
            dictionary.Add( "EntityTypeId", this.EntityTypeId );
            dictionary.Add( "EntityTypeQualifierColumn", this.EntityTypeQualifierColumn );
            dictionary.Add( "EntityTypeQualifierValue", this.EntityTypeQualifierValue );
            dictionary.Add( "Name", this.Name );
            dictionary.Add( "SourcesTypeId", this.SourcesTypeId );
            dictionary.Add( "Id", this.Id );
            dictionary.Add( "Guid", this.Guid );
            return dictionary;
        }

        /// <summary>
        /// Creates a dynamic object.
        /// </summary>
        /// <returns></returns>
        public virtual dynamic ToDynamic()
        {
            dynamic expando = new ExpandoObject();
            expando.IsSystem = this.IsSystem;
            expando.EntityTypeId = this.EntityTypeId;
            expando.EntityTypeQualifierColumn = this.EntityTypeQualifierColumn;
            expando.EntityTypeQualifierValue = this.EntityTypeQualifierValue;
            expando.Name = this.Name;
            expando.SourcesTypeId = this.SourcesTypeId;
            expando.Id = this.Id;
            expando.Guid = this.Guid;
            return expando;
        }

        /// <summary>
        /// Copies the model property values to the DTO properties
        /// </summary>
        /// <param name="model">The model.</param>
        public void CopyFromModel( IEntity model )
        {
            if ( model is NoteType )
            {
                var noteType = (NoteType)model;
                this.IsSystem = noteType.IsSystem;
                this.EntityTypeId = noteType.EntityTypeId;
                this.EntityTypeQualifierColumn = noteType.EntityTypeQualifierColumn;
                this.EntityTypeQualifierValue = noteType.EntityTypeQualifierValue;
                this.Name = noteType.Name;
                this.SourcesTypeId = noteType.SourcesTypeId;
                this.Id = noteType.Id;
                this.Guid = noteType.Guid;
            }
        }

        /// <summary>
        /// Copies the DTO property values to the entity properties
        /// </summary>
        /// <param name="model">The model.</param>
        public void CopyToModel ( IEntity model )
        {
            if ( model is NoteType )
            {
                var noteType = (NoteType)model;
                noteType.IsSystem = this.IsSystem;
                noteType.EntityTypeId = this.EntityTypeId;
                noteType.EntityTypeQualifierColumn = this.EntityTypeQualifierColumn;
                noteType.EntityTypeQualifierValue = this.EntityTypeQualifierValue;
                noteType.Name = this.Name;
                noteType.SourcesTypeId = this.SourcesTypeId;
                noteType.Id = this.Id;
                noteType.Guid = this.Guid;
            }
        }
    }
}
