//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//

using System;
using System.Linq;

using Rock.Data;

namespace Rock.Core
{
    /// <summary>
    /// NoteType Service class
    /// </summary>
    public partial class NoteTypeService : Service<NoteType, NoteTypeDto>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NoteTypeService"/> class
        /// </summary>
        public NoteTypeService()
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NoteTypeService"/> class
        /// </summary>
        public NoteTypeService(IRepository<NoteType> repository) : base(repository)
        {
        }

        /// <summary>
        /// Creates a new model
        /// </summary>
        public override NoteType CreateNew()
        {
            return new NoteType();
        }

        /// <summary>
        /// Query DTO objects
        /// </summary>
        /// <returns>A queryable list of DTO objects</returns>
        public override IQueryable<NoteTypeDto> QueryableDto( )
        {
            return QueryableDto( this.Queryable() );
        }

        /// <summary>
        /// Query DTO objects
        /// </summary>
        /// <returns>A queryable list of DTO objects</returns>
        public IQueryable<NoteTypeDto> QueryableDto( IQueryable<NoteType> items )
        {
            return items.Select( m => new NoteTypeDto()
                {
                    IsSystem = m.IsSystem,
                    EntityTypeId = m.EntityTypeId,
                    EntityTypeQualifierColumn = m.EntityTypeQualifierColumn,
                    EntityTypeQualifierValue = m.EntityTypeQualifierValue,
                    Name = m.Name,
                    SourcesTypeId = m.SourcesTypeId,
                    Id = m.Id,
                    Guid = m.Guid,
                });
        }
    }
}
