// <auto-generated />
namespace Rock.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GroupTypeSpecificGroups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GroupTypeSpecificGroups));
        
        string IMigrationMetadata.Id
        {
            get { return "201211051630211_GroupTypeSpecificGroups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
